services:
- type: web
name: minitransfer
env: python
region: oregon
plan: starter
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --threads=4 --timeout=120"
envVars:
- key: PYTHON_VERSION
value: 3.11.9
- key: SECRET_KEY
generateValue: true
disks:
- name: uploads
mountPath: /opt/render/project/src/uploads
sizeGB: 1
